services:
  postgres:
    image: postgres:latest
    container_name: postgres-empresaluz
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=empresaluz
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - empresaluz-network
    restart: always

volumes:
  postgres-data:

networks:
  empresaluz-network:
    driver: bridge
